In [356]:
import pandas as pd
import openpyxl
import os
import glob, re

In [357]:
def read_excel(files, sheet):
    dfs = []
    for file in files:
        data = pd.read_excel(file, sheet_name=sheet, index_col=0)
        name = os.path.splitext(os.path.basename(file))[0]
        data['model'] = name
        match = re.search(r'lr[\d.]+_(\d+)_', name)
        if match:
            data['epochs'] = int(match.group(1))
        match_model = re.search(r'model_.*?_e_(.*?)_lr', name)
        if match_model:
            data['id'] = match_model.group(1)
        dfs.append(data)
    df = pd.concat(dfs,ignore_index=True)
    return df

In [358]:
def arrange_data(df, error):
    df = df.pivot(index='model', columns='error', values=error)
    return df

In [359]:
def min_vals(df, error):
    df1 = df.apply(lambda x: pd.Series({'model':x.idxmin(), error:x.min()})).T
    return df1

In [360]:
path = "model_Fe_Si_B_260311/**/test_res/*_test.xlsx"

In [361]:
files = glob.glob(path, recursive=True)

In [362]:
df = read_excel(files, 'errors')
df = df[['model', 'id', 'epochs']+[c for c in df.columns if c not in ['model', 'id', 'epochs']]]
df

,model,id,epochs,error,rmse,mae,r2
0,model_rnd_e_matpes_lr0.0001_80_10_test,matpes,80,test_energy,43.019987,26.794243,0.989961
1,model_rnd_e_matpes_lr0.0001_80_10_test,matpes,80,train_energy,100.808691,27.309964,0.950446
2,model_rnd_e_matpes_lr0.0001_80_10_test,matpes,80,test_force,0.159534,0.120127,0.996744
3,model_rnd_e_matpes_lr0.0001_80_10_test,matpes,80,train_force,0.139589,0.107203,0.997482
4,model_rnd_e_matpes_lr0.0001_40_10_test,matpes,40,test_energy,49.126072,28.338427,0.986909
5,model_rnd_e_matpes_lr0.0001_40_10_test,matpes,40,train_energy,103.295626,27.930106,0.947971
6,model_rnd_e_matpes_lr0.0001_40_10_test,matpes,40,test_force,0.162873,0.122402,0.996606
7,model_rnd_e_matpes_lr0.0001_40_10_test,matpes,40,train_force,0.152998,0.116890,0.996975
8,model_rnd_e_matpes_lr0.0001_60_10_test,matpes,60,test_energy,46.366162,30.922178,0.988339
9,model_rnd_e_matpes_lr0.0001_60_10_test,matpes,60,train_energy,102.324352,31.753122,0.948945
10,model_rnd_e_matpes_lr0.0001_60_10_test,matpes,60,test_force,0.160293,0.120646,0.996712
11,model_rnd_e_matpes_lr0.0001_60_10_test,matpes,60,train_force,0.146102,0.111942,0.997242

In [363]:
#df.loc[df['model']=='model_rnd_e_matpes_lr0.0001_40_10_test']

In [371]:
rmse = arrange_data(df, 'rmse')
mae = arrange_data(df, 'mae')
rmse

error,test_energy,test_force,train_energy,train_force
model,,,,
model_rnd_e_matpes_lr0.0001_40_10_test,49.126072,0.162873,103.295626,0.152998
model_rnd_e_matpes_lr0.0001_60_10_test,46.366162,0.160293,102.324352,0.146102
model_rnd_e_matpes_lr0.0001_80_10_test,43.019987,0.159534,100.808691,0.139589

In [365]:
min_vals(rmse, 'rsme')

                                               model        rsme
error
test_energy   model_rnd_e_matpes_lr0.0001_80_10_test   43.019987
test_force    model_rnd_e_matpes_lr0.0001_80_10_test    0.159534
train_energy  model_rnd_e_matpes_lr0.0001_80_10_test  100.808691
train_force   model_rnd_e_matpes_lr0.0001_80_10_test    0.139589

In [366]:
min_vals(mae, 'mae')

                                               model        mae
error
test_energy   model_rnd_e_matpes_lr0.0001_80_10_test  26.794243
test_force    model_rnd_e_matpes_lr0.0001_80_10_test   0.120127
train_energy  model_rnd_e_matpes_lr0.0001_80_10_test  27.309964
train_force   model_rnd_e_matpes_lr0.0001_80_10_test   0.107203

In [367]:
#df.loc[df['id']=='matpes']

In [368]:
#df.query('id == "matpes" & epochs in [80, 40]')

In [369]:
#fine_tuning = df.query('id == "matpes"')
#min_vals(fine_tuning, 'mae')

Reading the config errors

In [370]:
read_excel(files, 'config_errors')

,error,n_configs,rmse,mae,model,epochs,id
0,test_energy,48,71.363086,70.949337,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
1,test_energy,12,5.172613,4.808195,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
2,test_energy,11,6.651858,6.094816,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
3,test_energy,133,9.337885,8.338329,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
4,test_energy,8,130.143428,130.134035,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
5,train_energy,132,71.366529,71.100268,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
6,train_energy,39,5.244371,4.905662,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
7,train_energy,40,8.987460,7.774841,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
8,train_energy,590,9.358866,8.296824,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
9,train_energy,44,422.625468,188.505525,model_rnd_e_matpes_lr0.0001_80_10_test,80,matpes
10,test_energy,48,85.016510,84.704623,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
11,test_energy,12,17.979317,17.839549,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
12,test_energy,11,4.621235,3.363690,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
13,test_energy,133,5.523249,4.299808,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
14,test_energy,8,139.878783,139.871876,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
15,train_energy,132,85.858381,85.578720,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
16,train_energy,39,18.110166,17.941300,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
17,train_energy,40,6.571228,4.875505,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
18,train_energy,590,5.775843,4.554277,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
19,train_energy,44,426.637969,198.245319,model_rnd_e_matpes_lr0.0001_40_10_test,40,matpes
20,test_energy,48,75.152637,74.758138,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
21,test_energy,12,4.348577,3.927227,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
22,test_energy,11,4.854654,3.799697,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
23,test_energy,133,13.881465,13.173163,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
24,test_energy,8,140.777896,140.769620,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
25,train_energy,132,75.611405,75.335201,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
26,train_energy,39,4.652940,4.228887,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
27,train_energy,40,6.387306,5.088528,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
28,train_energy,590,13.931219,13.171885,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes
29,train_energy,44,425.754483,198.801387,model_rnd_e_matpes_lr0.0001_60_10_test,60,matpes